Repository kcp-dev/multicluster-provider, pull requests merged in 2025-03, with the labels that each got.

#4 Add Prow jobs for verify, lint and test
  .prow.yaml
  Makefile
  hack/run-tests.sh
  virtualworkspace/wildcard.go
Labels: release-note-none, lgtm, size/M, dco-signoff: yes, approved

#5 Add GitHub issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/pull_request_template.md
  .github/workflows/pr-verifier.yaml
Labels: release-note-none, size/L, lgtm, dco-signoff: yes, approved

#9 :bug: Start informers for objects that they haven't been started for yet
  examples/apiexport/main.go
  go.mod
  go.sum
  virtualworkspace/cache.go
  virtualworkspace/provider.go
  virtualworkspace/wildcard.go
Labels: release-note-none, lgtm, size/M, dco-signoff: yes, approved

#11 :seedling: Add gci for import sorting
  .golangci.yaml
  Makefile
  virtualworkspace/cache.go
  virtualworkspace/cluster.go
  virtualworkspace/forked_cache_reader.go
  virtualworkspace/indexes.go
  virtualworkspace/indexes_test.go
  virtualworkspace/provider.go
  virtualworkspace/wildcard.go
Labels: release-note-none, size/M, dco-signoff: yes

#12 :seedling: Add envtest
  .golangci.yaml
  Makefile
  client/client.go
  envtest/doc.go
  envtest/eventually.go
  envtest/internal/addr/addr_suite_test.go
  envtest/internal/addr/manager.go
  envtest/internal/addr/manager_test.go
  envtest/internal/certs/certs_suite_test.go
  envtest/internal/certs/tinyca.go
  envtest/internal/certs/tinyca_test.go
  envtest/internal/controlplane/auth.go
  envtest/internal/controlplane/auth_test.go
  envtest/internal/controlplane/controlplane_suite_test.go
  envtest/internal/controlplane/kubectl.go
  envtest/internal/controlplane/kubectl_test.go
  envtest/internal/controlplane/plane.go
  envtest/internal/controlplane/plane_test.go
  envtest/internal/controlplane/shard.go
  envtest/internal/controlplane/shard_test.go
  envtest/internal/controlplane/testdata/fake-1.19-apiserver.sh
  envtest/internal/controlplane/testdata/fake-1.20-apiserver.sh
  envtest/internal/flock/doc.go
  envtest/internal/flock/errors.go
  envtest/internal/flock/flock_other.go
  envtest/internal/flock/flock_unix.go
  envtest/internal/process/arguments.go
  envtest/internal/process/arguments_test.go
  envtest/internal/process/bin_path_finder.go
  envtest/internal/process/bin_path_finder_test.go
  envtest/internal/process/procattr_other.go
  envtest/internal/process/procattr_unix.go
  envtest/internal/process/process.go
  envtest/internal/process/process_suite_test.go
  envtest/internal/process/process_test.go
  envtest/scheme.go
  envtest/server.go
  envtest/testing.go
  envtest/workspaces.go
  go.mod
  go.sum
  hack/boilerplate/kubernetes/boilerplate.go.txt
  hack/run-tests.sh
  hack/verify-boilerplate.sh
  test/e2e/client_test.go
  test/e2e/suite_test.go
Labels: release-note-none, lgtm, size/XXL, dco-signoff: yes, approved

#13 :seedling: Add virtualworkspace e2e test
  envtest/internal/controlplane/plane.go
  envtest/internal/controlplane/shard.go
  test/e2e/apiexport_test.go
  test/e2e/suite_test.go
  virtualworkspace/provider.go
Labels: release-note-none, size/L, lgtm, dco-signoff: yes, approved

#15 :seedling: Update to `sigs.k8s.io/multicluster-runtime` (v0.20.4-alpha.6)
  .golangci.yaml
  examples/apiexport/main.go
  go.mod
  go.sum
  test/e2e/apiexport_test.go
  virtualworkspace/provider.go
Labels: release-note, lgtm, size/M, dco-signoff: yes, approved
